playMsg "WxNatural" "Aktuelle_Wetterdaten_von";
spellWord OE9XVI-6;
playSilence 200;
playMsg "WxNatural" "Stand";
playNumber 11;
playMsg "WxNatural" "Uhr";
playNumber 46;
playSilence 300;
playMsg "WxNatural" "Die_Temperatur_betraegt";
playNumber 10.0;
playMsg "MetarInfo" "unit_degrees";
playMsg "WxNatural" "bei_einer_Luftfeuchte_von";
playNumber 74;
playMsg "MetarInfo" "percent";
playSilence 300;
playMsg "WxNatural" "Der_Luftdruck_betraegt";
playMsg "WxNatural" "eintausend";
playNumber 1;
playMsg "MetarInfo" "unit_hPa";
playMsg "WxNatural" "und_ist_gleichbleibend";
playSilence 300;
playMsg "WxNatural" "Es_herrscht_Windstille";
playSilence 300;
playMsg "WxNatural" "Aktuell_kein_Niederschlag";
playSilence 200;
playNumber 0.5;
playMsg "MetarInfo" "unit_mm";
playMsg "WxNatural" "Niederschlag_letzten_24h";
playSilence 300;
playMsg "WxNatural" "Ende_der_Wetterdurchsage";
